-- (5) 박지성이구매한도서의출판사수
SELECT COUNT(DISTINCT PUBLISHER)
FROM BOOK B, ORDERS O, CUSTOMER C
--WHERE B.BOOKID = O.BOOKID AND O.CUSTID = (SELECT C.CUSTID FROM CUSTOMER C WHERE C.NAME = '박지성')
WHERE C.CUSTID = O.CUSTID AND O.BOOKID = B.BOOKID AND C.NAME = '박지성'
;

-- (6) 박지성이 구매한 도서의 이름, 가격, 정가와 판매가격의 차이
SELECT BOOKNAME, (B.PRICE-O.SALEPRICE) AS PRICEGAP
FROM BOOK B, ORDERS O, CUSTOMER C
--WHERE B.BOOKID = O.BOOKID AND O.CUSTID = (SELECT C.CUSTID FROM CUSTOMER C WHERE C.NAME = '박지성')
WHERE B.BOOKID = O.BOOKID AND O.CUSTID = C.CUSTID AND C.NAME = '박지성'
;


-- (7) 박지성이구매하지않은도서의이름
SELECT B.BOOKNAME
FROM BOOK B, ORDERS O
WHERE B.BOOKID = O.BOOKID AND O.CUSTID NOT IN(SELECT C.CUSTID FROM CUSTOMER C WHERE C.NAME = '박지성')
;

-- (8) 주문하지않은고객의이름(부속질의사용)
SELECT NAME
FROM CUSTOMER
WHERE CUSTID NOT IN(SELECT DISTINCT CUSTID FROM ORDERS)
;
SELECT C.NAME
FROM ORDERS O, CUSTOMER C
WHERE O.CUSTID(+) = C.CUSTID AND O.ORDERID IS NULL
;


-- (9) 주문금액의총액과주문의평균금액
SELECT SUM(SALEPRICE) AS TOTAL, AVG(SALEPRICE)
FROM ORDERS 
;

-- (10) 고객의 이름과 고객별 구매액
SELECT C.NAME, SUM(O.SALEPRICE) AS TOTAL -- 스칼라 부속질의 사용해보도록
FROM ORDERS O, CUSTOMER C
WHERE O.CUSTID = C.CUSTID
GROUP BY C.NAME
;
SELECT O.CUSTID, (SELECT C.NAME FROM CUSTOMER C WHERE O.CUSTID = C.CUSTID), SUM(SALEPRICE)
FROM ORDERS O
GROUP BY O.CUSTID
;

-- (11) 고객의 이름과 고객이 구매한 도서목록
SELECT C.NAME, B.BOOKNAME
FROM CUSTOMER C, ORDERS O, BOOK B
WHERE C.CUSTID = O.CUSTID AND O.BOOKID = B.BOOKID
ORDER BY C.NAME
;

-- (12) 도서의 가격(Book 테이블)과
-- 판매가격(Orders 테이블)의 차이가
-- 가장 많은 주문 
SELECT MAX(B.PRICE - O.SALEPRICE)
FROM ORDERS O, BOOK B
WHERE O.BOOKID = B.BOOKID
;
SELECT *
FROM ORDERS O JOIN BOOK B
ON O.BOOKID = B.BOOKID
WHERE B.PRICE - O.SALEPRICE = (SELECT MAX(B.PRICE - O.SALEPRICE)
                                FROM ORDERS O, BOOK B
                                WHERE O.BOOKID = B.BOOKID)
                                ;

--------------------------------------------------------------

-- (13) 도서의판매액평균보다자신의구매액평균이더높은고객의이름
SELECT C.NAME, AVG(SALEPRICE)
FROM CUSTOMER C, ORDERS O
WHERE O.CUSTID = C.CUSTID
GROUP BY C.NAME
HAVING AVG(O.SALEPRICE) > ALL (SELECT AVG(O.SALEPRICE) FROM ORDERS O)
;

--(1) 박지성이 구매한 도서의 출판사와 같은 출판사에서 도서를 구매한 고객의 이름
SELECT DISTINCT B.PUBLISHER
FROM ORDERS O, CUSTOMER C, BOOK B
WHERE O.CUSTID = C.CUSTID AND O.BOOKID = B.BOOKID AND C.NAME = '박지성'
;
SELECT *
FROM ORDERS O, CUSTOMER C, BOOK B
WHERE O.CUSTID = C.CUSTID AND O.BOOKID = B.BOOKID
;

--(2) 두 개 이상의 서로 다른 출판사에서 도서를 구매한 고객의 이름
SELECT DISTINCT C.NAME, B.PUBLISHER
FROM ORDERS O, CUSTOMER C, BOOK B, BOOK B2
WHERE O.CUSTID = C.CUSTID AND O.BOOKID = B.BOOKID AND B.PUBLISHER != B2.PUBLISHER
ORDER BY C.NAME
;

